name: Build, Analyze and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3
      
    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build . -t devopsport/nodeserver:latest

    - name: Push the Docker image to Docker Hub
      run: docker push devopsport/nodeserver:latest

  sonarQubeAnalysis:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectKey: your-sonarqube-project-key
        organization: your-sonarqube-organization
        scanner-mode: cli

  deploy:
    runs-on: ubuntu-latest
    needs: sonarQubeAnalysis

    steps:
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App for Containers
      uses: azure/webapps-container-deploy@v2
      with:
        app-name: your-app-name
        images: devopsport/nodeserver:latest
