name: Build, Analyze and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3
      
    - name: Log in to Docker Hub
      run: |
        echo "Logging in to Docker Hub..."
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      env:
        DEBUG: 1

    - name: Build the Docker image
      run: docker build . -t nodeserver:latest

    - name: List Docker images
      run: docker image ls

    - name: Tag Docker image
      run: docker tag nodeserver:latest devopsport2165/nodeserver:latest

    - name: Push the Docker image to Docker Hub
      run: docker push devopsport2165/nodeserver:latest

  sonarQubeAnalysis:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out the code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@main
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=vishalsubharthi
          -Dsonar.projectKey=c05fdd8f
  deploy:
    runs-on: ubuntu-latest
    needs: sonarQubeAnalysis

    steps:
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App for Containers
      uses: azure/webapps-deploy@v2
      with:
        app-name: your-app-name
        images: devopsport2165/nodeserver:latest
